version: 1

models:
  - name: sales
    description: "sales data"
    columns:
      - name: Store
        description: "Store ID"
        tests:
          - unique
          - not_null
      - name: Dept
        description: "Department ID"
        tests:
          - not_null
      - name: Date
        description: "Date of sales"
        tests:
          - not_null
      - name: Weekly_Sales
        description: "Weekly Sales"
        tests:
          - not_null
      - name: IsHoliday
        description: "Is the date holiday?"
        tests:
          - not_null
